name: build-caddy
on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4
      - name: Get image tag and login
        run: |
           export IMAGE_TAG=$(grep '^FROM' Dockerfile | head -n 1 |sed -n 's/^FROM [^:]*:\([^-]*\).*/\1/p')
           echo $IMAGE_TAG
           echo "correct_tag=$IMAGE_TAG" >> "$GITHUB_ENV"
           echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u Saschl --password-stdin
           echo "${{ secrets.DHI_TOKEN }}" | docker login dhi.io -u saschl --password-stdin


      - name: Build and push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/saschl/caddy:${{env.correct_tag}}
